### ISSUE TITLE
cal_best.cのデバッグ

### ISSUE THREAD

**Issue by intohay** [root2116/neutreeko_group5#1]
見つけたバグとして、condtion_arrayとかの配列のインデックスに〇〇_idが入ってるところが数箇所ある。〇〇_indexしか入らないのでは？

**Comment by intohay** [comment]
間違っているところは直しました

**Comment by atsu0905** [comment]
inv_graph_tableの辺の数がおかしいことが判明
make_graphのデバッグを行っています

**Comment by atsu0905** [comment]
配列をいじる前に初期化したら意図していたinv_graph_tableが無事に出来た
その結果再帰2回目までは意図する挙動をするようになったけど、それ以降はなんかバグってる
cal_best関数内のデバッグをこれから行います

**Comment by atsu0905** [comment]
解決（discord見てください）

**Comment by intohay** [comment]
ばんざーーーーーーーーーい
