### ISSUE TITLE
AIの名前について

### ISSUE THREAD

**Issue by intohay** [root2116/neutreeko_group5#2]
私たちが作ったAIに名前を授けましょう。

**Comment by intohay** [comment]
いい名前思いついたら書いてください

**Comment by intohay** [comment]
inv_graph_tableからinvを取ったら動いたということで、Inverseという名前はどうでしょうか？

**Comment by atsu0905** [comment]
遷移を逆向きに辿っていくのが勝敗決定アルゴリズムのポイントですしぴったりだと思います。
（inv_graph_tableからinvを取ったら………のくだりはもう忘れたい（））

**Comment by intohay** [comment]
確かにそっちの理由のほうがいいね

**Comment by intohay** [comment]
Inverseちゃんに決定
